drop table geek if exists cascade;
drop table interet if exists cascade;
drop sequence geek_seq if exists;
drop sequence interet_seq if exists;
drop sequence audit_seq if exists;

create table geek (
	id numeric not null,
	nom varchar(255) not null,
	prenom varchar(255) not null,
	age numeric not null,
	genre varchar(20) not null,
	cptvisite numeric not null,
	primary key (id)
);

create table interet (
	id numeric not null,
	interet varchar(255) not null,
	id_geek numeric not null,
	primary key (id),
	foreign key (id_geek) references geek(id)
);

create table audit(
	id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) not null,
	dateVisite varchar(50),
	idGeek numeric not null,
	ip varchar(50) not null,
	primary key (id),
	foreign key (idGeek) references geek(id)
);

create sequence geek_seq start with 1;
create sequence audit_seq start with 1;
create sequence interet_seq start with 1;

--INSERTION DANS LA BASE DE DONNEES--

INSERT INTO "PUBLIC"."GEEK"( "ID", "NOM", "PRENOM", "AGE", "GENRE", "CPTVISITE" ) VALUES (1, 'Rosset', 'Melanie', 22, 'Féminin',0)
INSERT INTO "PUBLIC"."GEEK"( "ID", "NOM", "PRENOM", "AGE", "GENRE", "CPTVISITE" ) VALUES (2, 'Hubert', 'Florent', 24,'Masculin',0)
INSERT INTO "PUBLIC"."GEEK"( "ID", "NOM", "PRENOM", "AGE", "GENRE", "CPTVISITE" ) VALUES (3, 'Landat', 'Frederic', 23,'Masculin',0)					

INSERT INTO "PUBLIC"."INTERET" ( "ID", "INTERET", "ID_GEEK" ) VALUES (1, 'c', 2)
INSERT INTO "PUBLIC"."INTERET" ( "ID", "INTERET", "ID_GEEK" ) VALUES (2, 'Java', 1)
INSERT INTO "PUBLIC"."INTERET" ( "ID", "INTERET", "ID_GEEK" ) VALUES (3, 'Java', 3)
INSERT INTO "PUBLIC"."INTERET" ( "ID", "INTERET", "ID_GEEK" ) VALUES (4, 'php',	3)
INSERT INTO "PUBLIC"."INTERET" ( "ID", "INTERET", "ID_GEEK" ) VALUES (5, 'Aventure', 1)
INSERT INTO "PUBLIC"."INTERET" ( "ID", "INTERET", "ID_GEEK" ) VALUES (6, 'Jeux de rôles', 2)
INSERT INTO "PUBLIC"."INTERET" ( "ID", "INTERET", "ID_GEEK" ) VALUES (7, 'Jeux de rôles', 3)
INSERT INTO "PUBLIC"."INTERET" ( "ID", "INTERET", "ID_GEEK" ) VALUES (8, 'Stratégie', 1)
INSERT INTO "PUBLIC"."INTERET" ( "ID", "INTERET", "ID_GEEK" ) VALUES (9, 'Stratégie', 2)





